---
# tasks file for pathsList
- name: Read the paths
  script:
    inline: |
      import yaml

      with open('/paths.yml') as f:
          paths = yaml.load(f, Loader=yaml.FullLoader)
      print(paths)
